### PR TITLE
First pull request

### PR DESCRIPTION
**Pull request by gabriel-silveira**
- Login
- Basic algorithm data management

### CODE REVIEW

**Comment by viniciusandrade** [comment]
Opa @gabriel-silveira após executar o build da api usando:

docker build -t clinical-algorithms-api . 

e tentando subir um container usando:

docker run --rm -p 8081:80 clinical-algorithms-api

tenho o seguinte out:

INFO:     Will watch for changes in these directories: ['/code']
INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
INFO:     Started reloader process [1] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/code/app/main.py", line 2, in <module>
    from routers import account, algorithms
ModuleNotFoundError: No module named 'routers'
INFO:     Stopping reloader process [1]

Poderia verificar se faltou algo da minha parte ou no código para que eu possa prosseguir?

Obrigado

**Comment by viniciusandrade** [comment]
obs: só para garantir também fiz o build usando **--no-cache** mas o erro persiste.

**Comment by gabriel-silveira** [comment]
> obs: só para garantir também fiz o build usando **--no-cache** mas o erro persiste.

@viniciusandrade Estou analisando aqui e já te dou uma resposta.

**Comment by gabriel-silveira** [comment]
@viniciusandrade Fiz uma atualização na estrutura de pacotes do projeto. Agora acredito que vai funcionar.
Também vai precisar criar as variáveis de ambiente no container.

**Comment by viniciusandrade** [comment]
@gabriel-silveira tive que fazer um ajuste pontual no Dockerfile para copiar o .env para dentro do container no momemento do build somente para validar e consegui subir o container da API. Obrigado.

**Pull request merged**
